version: '3'

services:
  python:
    build:
      context: ./project/python
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/python/:/python
    ports:
      - "8000:8000"

  java:
    build:
      context: ./project/java
      dockerfile: Dockerfile
    volumes:
      - ./project/java/:/usr/src/app
    entrypoint: sh -c 'find src/ | entr mvn clean compile exec:java --batch-mode --quiet'
